### ISSUE TITLE
[DOCUMENTATION]: missing documentation on how to load conf-file from other locations

### ISSUE THREAD

**Issue by MonkeyCanCode** [polaris-catalog/polaris#45]
With eclipse-link extension enabled, an end-user will be able to update `polaris-server.yml` to the following to use a persistent backend:
```
metaStoreManager:
    type: eclipse-link
    conf-file: xxx
    persistence-unit: xxx
```

However, this seems to be only able to read off files from META-INF dirs. As those dirs will get packed into the JAR, it is not ideal for prod deployment as well as source code check-in for version control. Is there any way for an end-user to set the conf-file location to other path instead (e.g. /etc/polaris/config/persistence.xml)?
